### ISSUE TITLE
Put everything in a namespace

### ISSUE THREAD

**Issue by mrzv** [LEW21/yieldxx#5]
I think this is a super-useful library, and I hope to use it in lots of projects now that it has a license. As such it would be nice to put everything in a namespace to avoid name clashes. I can create a pull-request, but it's probably more appropriate for you to choose the name for the namespace yourself.

**Comment by LEW21** [comment]
Done. The namespace is called xx::, and the project name was changed to yieldxx - by analogy to https://github.com/LEW21/variantxx
